"""describe your migratiosssn

Revision ID: 369440e96d69
Revises: 
Create Date: 2025-09-19 19:45:04.892792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369440e96d69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # telegram_id remains nullable - existing sellers will have NULL telegram_id
    # and it gets filled when they authenticate through the bot
    
    # Drop the unique constraint on chat_id first
    op.drop_constraint('sellers_chat_id_key', 'sellers', type_='unique')
    
    # Drop the chat_id column
    op.drop_column('sellers', 'chat_id')
    
    # telegram_id is already nullable, so no need to change it
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the chat_id column (nullable since we don't have this data)
    op.add_column('sellers', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    
    # Create unique constraint on chat_id (may fail if there are NULL values)
    # NOTE: This may require manual data cleanup before running
    # op.create_unique_constraint('sellers_chat_id_key', 'sellers', ['chat_id'])
    
    # telegram_id is already nullable, no change needed
    # ### end Alembic commands ###
